# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 03:20
from __future__ import unicode_literals

import ads.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_every_qty_items', models.IntegerField(blank=True, null=True)),
                ('free_items', models.IntegerField(blank=True, null=True)),
                ('fixed_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('min_qty_before_fixed_discount', models.IntegerField(blank=True, null=True)),
                ('customer', models.ManyToManyField(to='ads.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.PositiveSmallIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Customer')),
            ],
            bases=(ads.models.PricingRules, models.Model),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='ads.OrderItem', to='ads.Product'),
        ),
        migrations.AddField(
            model_name='discount',
            name='product',
            field=models.ManyToManyField(to='ads.Product'),
        ),
    ]
